name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Add docker to sudo group
      run: sudo usermod -aG docker $USER
    - name: Run all docker containers 
      run: docker-compose up -d
    - name: Build with Maven
      run: mvn -B package --file pom.xml